"""Initial migration.

Revision ID: 66f2dbb946c5
Revises: 
Create Date: 2024-10-05 17:29:45.341596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f2dbb946c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance_log', schema=None) as batch_op:
        batch_op.drop_column('points_earned')

    # ### end Alembic commands ###
